#!/bin/sh
# mountapifs
# runs a command while holding certain essential API mount-points in a chroot prefix open.
# the mount points are cleaned up on termination.
# /sys inside the prefix is not mounted unless requested via env var.

err() { echo "$@" >&2; }
usage() {
	err "Usage: $0 prefix command [args...]";
	exit 1;
}

r="$1";
shift;
if test -z "$r"; then usage; fi;
if test $# -lt 1; then usage; fi;

# at least for pacman installations, not the entire /dev needs to be accessible.
# instead just mount a restricted tmpfs with the essentials that could be used in a script.
spawndev() {
	mount-minimal-dev "$1";
}



cleanup() {
	mountapifs.stop "$r";
}
trap cleanup EXIT;



mountapifs.start "$r" && "$@" || exit $?;
